### ISSUE TITLE
At least one of the fields must be specified

### ISSUE THREAD

**Issue by jjrom** [stac-extensions/sat#2]
The documentation and the subsequent schema specify that "at least one of the sat fields must be specified".

This requirement could cause implementation issue. For instance, suppose a server that provides two collections, one that contains items with "sat" properties and the other with items that do not. The server endpoint would indicate the support of the "sat" extension in the "conformsTo". However, json validation would fail for items that do not contains sat properties.

Can we remove this requirement ?

**Comment by emmanuelmathot** [comment]
In my understanding, the conformance declaration is different from the `stac_extensions` is items. The former does not imply the latter. if items in results do not have `sat` properties then the declaration in `stac_extensions` of the items must not be present. Declaring extensions without properties would lead to documents with all extensions systematically to cover all cases. Implementations must be able rely on the stac_extensions declarations to load adequate modules.

**Comment by jjrom** [comment]
Ok I understand but in my implementation, the extensions support is defined at the core level and provided in each items. So to conforms to this requirement, this require before the rendering that the server to check individually all items properties and eventually remove the extension from stac_extensions when at least one property of the extension is not present. And this for all extensions...

I saw that this requirement is present in all extensions and I don't understand its purpose. Why just not defining extensions with properties that are all optional ?

**Comment by emmanuelmathot** [comment]
because as described in the [item spec](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#stac_extensions), this is "A list of extensions the Item implements" and "this list must only contain extensions that extend the Item specification itself".

**Comment by jjrom** [comment]
The issue is not that the "list must only contain extensions that extend the Item specification itself" but that in all extensions at least one element is required to be present in item. I just don't understand the rationale of this constraint.
@m-mohr can you comment on this ?

**Comment by m-mohr** [comment]
Yes, an extension is only useful if data is provided. As such, we want to validate that if an extension is specified to be implemented in an item, it must also provide data. Thus we require at least one field to be present. I don't understand the issue to be honest. Could you give an example of why this is an issue?

**Comment by jjrom** [comment]
In my implementation the STAC extensions are defined at the collection level. Each collection is defined by a model (e.g. SatelliteModel, OpticalModel, etc.).

For instance, the Sentinel-2 collection inherits both from the OpticalModel and the SatelliteModel. From a STAC point of view it means that the collection supports the "eo", "sat" and "view" extensions.

Now resto is very permissive on the metadata content you can ingest. In particular, suppose you have a bunch of metadata files issued from satellite acquisition. These metadata are incomplete - they have spatiotemporal information but any of the requested property from the "sat" extension. However since these metadata are linked to a satellite acquisition, it is logical that they are ingested in a collection defined by the SatelliteModel.

Fundamentally, the items belongs to a satellite collection even it is does not provide any of the "sat" property extension. But with the constraint to have at least one "sat" property, the resulting item would be invalid since it will specify the "sat" extension

**Comment by m-mohr** [comment]
Well, but that's your implementation detail. Why should we bother here how your internal implementation looks like? It seems you are using the schema URLs in stac_extensions for something they are not made to be used for.

**Comment by m-mohr** [comment]
By the way, you are actually not allowed to specify schemas in the collection that are not used there:

>  This must not declare the extensions that are only implemented in child Collection objects or child Item objects.

**Comment by jjrom** [comment]
@m-mohr Thanks for the feedback on unallowed stac_extensions at the collection level

I agree it is not an issue at the extension level since they all follow the same pattern requirement.
