### ISSUE TITLE
Satellite Location

### ISSUE THREAD

**Issue by sanjosealbacete** [stac-extensions/sat#3]
Hi there,

Users request information related to the satellite location (altitude, latitude, longitude). It would be useful if it is included in the Satellite Extension Specification-

Many thanks and best regards,
Tony

**Comment by emmanuelmathot** [comment]
Hello. Do you mean information such as the orbit state vectors?

**Comment by matthewhanson** [comment]
I think you might mean the sub-satellite point at the time of acquisition? (I think so because lat/lon).

Orbital state vectors would also be useful for some people I think, but these should be in ECI coordinates.

**Comment by emmanuelmathot** [comment]
I intended to make a PR to add the orbit state vector (pos + vel [+ acc]) in ECI ref as it is useful to search for correlated scenes (e.g. interferometry).
I never used the sub-sat point. is it the azimuth pos (lat/lon/alt)? What is the use case?

**Comment by sanjosealbacete** [comment]
Hi @emmanuelmathot,

The use case is related to atmospheric correction purposes. Some users need the info related to the position/location of the satellite at the moment of the capture along with sun elevation, sun azimuth and other parameters to calculate the BOA reflactance.
BR,
Tony

**Comment by sanjosealbacete** [comment]
Hi @emmanuelmathot and @matthewhanson ,

Do you consider that this information could be included into the Satellite Extension Specification?

BR,
Tony

**Comment by m-mohr** [comment]
The platform (mean) altitude would also be useful to have for the CEOS ARD extension (Radar profile, req. 1.6.5).
