### ISSUE TITLE
Rename sat:cycle to sat:orbit_cycle

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/sat#7]

**Comment by emmanuelmathot** [comment]
done in https://github.com/stac-extensions/sat/commit/65887837be13cd37d2133aada05651f71a86098b

**Comment by m-mohr** [comment]
Thanks. You may want to remove the [.vscode/settings.json](https://github.com/stac-extensions/sat/commit/65887837be13cd37d2133aada05651f71a86098b#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357), which seems like an accidentally committed file.
